### ISSUE TITLE
Feature: User can add exercises they’ve done for each day.

### ISSUE THREAD

**Issue by leanne-vu** [leanne-vu/Work-it-Out#1]
## 💰 Motivation

User can add exercises they’ve done for each day.

## 📐 Plan

Users can see the home screen, press on the "Add a Workout" button, and are moved to a form.  The form will allow the user to add an exercise for the day. This information is stored.

## 🖼️ Wireframes
**User can view the homescreen view and add form view mobile**
<img width="609" alt="Screen Shot 2022-12-28 at 9 29 57 AM" src="https://user-images.githubusercontent.com/113091744/209850383-0623ff01-f5cd-4da3-a99f-d183ed63c679.png">

**User can view the homescreen view and add form view desktop**
<img width="893" alt="Screen Shot 2022-12-28 at 9 30 25 AM" src="https://user-images.githubusercontent.com/113091744/209850401-931664bb-4c56-43dc-bcfe-2697722e31de.png">

## ✅ Task List
- [x] Create database with appropriate schema to store information.
- [x] Utilize HTML and CSS to splash screen and button to add a workout.
- [x] Utilize hashrouting to take users to form when they click on button.
- [x] Utilize react to create form to add a workout when clicking on button.
- [x] Make sure form has the appropriate "required" attribute for each input.
- [x] Issue the appropriate HTTP request to the Node/Express server.
- [x] Send SQL request to the database to POST.
- [x] Respond to web server with appropriate status code, if successful, reset form.
- [x] Ensure hash routing for both splash screen and form are correct.
- [x] Ensure that refreshing the pages shows the same view as before refreshing.
- [x] Clean up all unnecessary styling.
- [x] Test the app some more in a private browsing tab.
- [x] Fix all errors.
