### ISSUE TITLE
Feature: User can view workouts they’ve done on different days

### ISSUE THREAD

**Issue by leanne-vu** [leanne-vu/Work-it-Out#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view workouts they’ve done on different days

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users may press on "Workouts" and view cards of different days and their workouts. When they click on the card, they will see details about that day's workout and its exercises.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

**User can view in mobile**
<img width="517" alt="Screen Shot 2022-12-28 at 9 51 55 AM" src="https://user-images.githubusercontent.com/113091744/209852748-7c950051-4e79-4e8e-9733-78dae88df06c.png">

**user can view in desktop**
<img width="747" alt="Screen Shot 2022-12-28 at 9 51 34 AM" src="https://user-images.githubusercontent.com/113091744/209852731-0e2c8420-1abe-49ea-945a-545648ed02f5.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to handle get requests
- [x] Update `server/index.js` to handle get requests via ID.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to open a menu to navigate to different screens.
- [x] Create dropdown menu that toggles between months on same route.
- [x] Create a component to view workouts from different months (drop down menu)
- [x] Client receives details of workout upon click.
- [x] Create a component that displays each workout's details upon click. 

### 🧑‍⚕️ Clean Up Tasks
 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
