### ISSUE TITLE
Feature: User can edit workouts they’ve done for each day

### ISSUE THREAD

**Issue by leanne-vu** [leanne-vu/Work-it-Out#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can edit workouts they’ve done for each day

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users may press on edit button of each workout, they'll be transferred to the edit form.  After edit, the screen should be updated with edits.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

**User can view in mobile**
<img width="394" alt="Screen Shot 2022-12-28 at 10 08 43 AM" src="https://user-images.githubusercontent.com/113091744/209854564-0609140d-e6da-4c8e-8956-55349705fb28.png">

**user can view in desktop**
<img width="593" alt="Screen Shot 2022-12-28 at 10 09 12 AM" src="https://user-images.githubusercontent.com/113091744/209854580-bd733602-b562-4c31-8576-1bb9b23ca4b4.png">
## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` with a new query to update the database for the chosen ID.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] When user presses edit button, they are taken to an edit form
- [x] Edit form has prefilled information 
- [x] When they submit the form, they are taken back to previous workout page.
- [x] Details of workouts reflect the edits made.
- [x] Going back to form gives empty form.

### 🧑‍⚕️ Clean Up Tasks
 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
