### ISSUE TITLE
Feature: User can delete exercises they’ve done for each day.

### ISSUE THREAD

**Issue by leanne-vu** [leanne-vu/Work-it-Out#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete exercises they’ve done for each day.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users may delete individual exercises added by pressing delete button and confirming. This will delete the exercise from the current view and from storage.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

**User can view in mobile**
<img width="396" alt="Screen Shot 2022-12-28 at 10 51 35 AM" src="https://user-images.githubusercontent.com/113091744/209858990-f094c944-5398-4fed-b020-6dfa12bdc42e.png">

**user can view in desktop**
<img width="589" alt="Screen Shot 2022-12-28 at 10 51 25 AM" src="https://user-images.githubusercontent.com/113091744/209858982-e85820b9-61f9-477e-a23b-85d36ddb30b6.png">
## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` with a new query to delete from both tables in database for the chosen ID.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create delete button for details popup.
- [x] Pressing on button takes user back to workouts list
- [x] Make sure user returns to workout list and it is updated.

### 🧑‍⚕️ Clean Up Tasks
 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
