### ISSUE TITLE
Feature: User can find new workout ideas.

### ISSUE THREAD

**Issue by leanne-vu** [leanne-vu/Work-it-Out#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can find new workout ideas.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User may go to "idea" tab and press a button to generate workout ideas.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

**User can view in mobile**
<img width="414" alt="Screen Shot 2022-12-28 at 10 53 20 AM" src="https://user-images.githubusercontent.com/113091744/209859214-fb25f509-c1b3-40fd-bd76-eb9fa23d5412.png">

**user can view in desktop**
<img width="588" alt="Screen Shot 2022-12-28 at 10 53 40 AM" src="https://user-images.githubusercontent.com/113091744/209859255-4ff4c64d-f21a-4e61-8502-ea2875f0b2a6.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Server handles get request from api,  sends back to client.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] User is able to click on ideas in menu and is taken to a new idea page
- [x] Create button that will generate the ideas.
- [x] fetch request to server end based on offset number.
- [x] URL reflects the offset number.
### 🧑‍⚕️ Clean Up Tasks
 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
