### ISSUE TITLE
Feature: User can add new exercise idea they want to try to a list.

### ISSUE THREAD

**Issue by leanne-vu** [leanne-vu/Work-it-Out#6]
> ##### What capability will users have when this feature is merged?

User can add new exercise idea they want to try to a list.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can press on star of each exercise they want to save to a list.  This will add it to storage. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

**User can view in mobile**
<img width="418" alt="Screen Shot 2022-12-28 at 10 55 41 AM" src="https://user-images.githubusercontent.com/113091744/209859465-4d39ade8-43af-4f04-a4d2-065b2a457616.png">

**user can view in desktop**
<img width="600" alt="Screen Shot 2022-12-28 at 10 55 27 AM" src="https://user-images.githubusercontent.com/113091744/209859475-3563a0d2-e92e-4029-adf2-280f5c3bbf56.png">
## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Server handles post request from client,  auto-increments.
- [x] Server handles get request from client for bookmarks page.
- [x] Appropriate errors are given for duplicates.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] User is able to click on a star and make a fetch post request to the server.
- [x] Post request targets a single exercise.
- [x] Compare list on page to saved data, color stars accordingly to which ones are already saved upon post.
- [x] Create bookmarks page to see all bookmarks, accessed through menu.
- [x] Add button on idea page to go to bookmarks page.
- [x] Bookmark page makes a get request for saved exercise ideas.
- [x] Fix reloading of page.
- [x] Stars are click targets, cursor pointer.
### 🧑‍⚕️ Clean Up Tasks
 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
