### ISSUE TITLE
Feature: User can delete workout ideas from the list.

### ISSUE THREAD

**Issue by leanne-vu** [leanne-vu/Work-it-Out#7]
> ##### What capability will users have when this feature is merged?

User can delete exercise ideas from the list.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can press on star of each exercise they want to take off the star list.  This will delete it from storage. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

**User can view in mobile**
<img width="434" alt="Screen Shot 2022-12-28 at 10 58 19 AM" src="https://user-images.githubusercontent.com/113091744/209859730-b027004f-40d2-4de1-835f-2804d89903d7.png">

**user can view in desktop**
<img width="599" alt="Screen Shot 2022-12-28 at 10 58 27 AM" src="https://user-images.githubusercontent.com/113091744/209859733-864ef43b-614a-4c55-a650-3a23ec75e0b1.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Server handles delete request from client for bookmarks page and ideas page.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Client can press on gold star on idea page and delete entry from bookmark page, change star color on page to grey.
- [x] Client can press on bookmark's star no bookmark page and delete from page.
- [x] If there are no bookmarks, client will see "no bookmarks heading."
### 🧑‍⚕️ Clean Up Tasks
 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
