### ISSUE TITLE
Feature: User can view how much they’ve worked out in a month (graph)

### ISSUE THREAD

**Issue by leanne-vu** [leanne-vu/Work-it-Out#8]
> ##### What capability will users have when this feature is merged?

User can view how much they’ve worked out in a month (graph)

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can press on "tracker" button to see a graph that details how many days they've worked out per month.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

**User can view in mobile**
<img width="432" alt="Screen Shot 2022-12-28 at 11 00 32 AM" src="https://user-images.githubusercontent.com/113091744/209859977-d78d18e7-0aea-4400-b369-f93462ab299c.png">

**user can view in desktop**
<img width="632" alt="Screen Shot 2022-12-28 at 11 00 08 AM" src="https://user-images.githubusercontent.com/113091744/209859937-d5a718be-d683-449c-b4e3-048a83520acd.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Server handles get request for workouts.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Upon entering tracker page, fetch get request workouts and store into this.state
- [x] Create a function that returns an array with the number of workouts per month.
- [x] Render bar graph component with the data as the function's result.
- [x] Stylize bar graph with appropriate labels, colors, etc.
- [x] Create "total workouts" section that displays the total number of workouts.

### 🧑‍⚕️ Clean Up Tasks
 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
